doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        schema_filter: ~^(?!caf_bus|caf_bus_lieu_destination|caf_content_html|caf_destination|caf_evt_destination)~
        default_table_options:
            charset:              utf8mb4
            collate:              utf8mb4_unicode_ci # when using doctrine/dbal 2.x
            collation:            utf8mb4_unicode_ci # when using doctrine/dbal 3.x

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
