# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    http_method_override: false
    handle_all_throwables: true
    annotations: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name:        clubalpin
        handler_id:  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        gc_maxlifetime: 259200 # 3 days
        cookie_lifetime: 10800 # 3 hours
        cookie_httponly: true
        cookie_secure: 'auto'
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
        default_uri: '%env(ROUTER_CONTEXT_SCHEME)%://%env(ROUTER_CONTEXT_HOST)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
