framework:
    messenger:
        # default failure transport
        failure_transport: failed

        transports:
            mails:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 10000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0

            failed: 'doctrine://default?queue_name=failed'

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': mails

        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection
                    - App\Bridge\Messenger\PublishedTimestampMiddleware
