when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            # Réduire le bruit: on ignore les erreurs attendues (404/403) côté Sentry
            ignore_exceptions:
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
                - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
        register_error_listener: false
        register_error_handler: false
