version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
      docker_layer_caching: true

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "ba:5a:94:59:70:b4:28:07:1f:38:ea:1e:66:69:b2:52"

      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
#      - run:
#          name: Check connection with deployment server
#          command: |
#            ssh-keyscan 141.94.251.125 >> ~/.ssh/known_hosts;
#            LANG=en_US.utf8 LC_ALL=en_US.utf8 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kahe0589@109.234.162.184 -J jump-user@141.94.251.125 echo "Successfully connected to prod server";
      - run:
          name: Build Docker image, run tests and prepare package
          command: |
            make build up composer-install setup-db migrate env=test
            make php-cs
            make phpstan
            make phpunit

            case ${CIRCLE_BRANCH} in
                "production" )
                    cp infrastructure/confs/production/robots.txt public/robots.txt
                    cp infrastructure/confs/production/.env.prod .
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$PROD_DB_PASSWORD/g" .env.prod
                    sed -i "s/DB_USER_TO_REPLACE/$PROD_DB_USER/g" .env.prod
                    sed -i "s/DB_NAME_TO_REPLACE/$PROD_DB_NAME/g" .env.prod
                    cp legacy/config/www.clubalpinlyon.fr/config.php legacy/config/config.php
                    sed -i "s/ADMIN_PASSWORD_TO_REPLACE/$PROD_ADMIN_PASSWORD/g" "legacy/config/www.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "legacy/config/www.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "legacy/config/config.php"
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$PROD_DB_PASSWORD/g" "legacy/config/config.php"
                    sed -i "s/DB_USER_TO_REPLACE/$PROD_DB_USER/g" "legacy/config/config.php"
                    sed -i "s/DB_NAME_TO_REPLACE/$PROD_DB_NAME/g" "legacy/config/config.php"
                    cp legacy/config/www.clubalpinlyon.fr/params.php legacy/config/params.php
                  ;;
                "main" )
                    cp infrastructure/confs/staging/robots.txt public/robots.txt
                    cp infrastructure/confs/staging/.env.prod .
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$DEV_DB_PASSWORD/g" .env.prod
                    sed -i "s/DB_USER_TO_REPLACE/$DEV_DB_USER/g" .env.prod
                    sed -i "s/DB_NAME_TO_REPLACE/$DEV_DB_NAME/g" .env.prod
                    cp legacy/config/test.clubalpinlyon.fr/config.php legacy/config/config.php
                    sed -i "s/ADMIN_PASSWORD_TO_REPLACE/$DEV_ADMIN_PASSWORD/g" "legacy/config/test.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "legacy/config/test.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "legacy/config/config.php"
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$DEV_DB_PASSWORD/g" "legacy/config/config.php"
                    sed -i "s/DB_USER_TO_REPLACE/$DEV_DB_USER/g" "legacy/config/config.php"
                    sed -i "s/DB_NAME_TO_REPLACE/$DEV_DB_NAME/g" "legacy/config/config.php"
                    cp legacy/config/www.clubalpinlyon.fr/params.php legacy/config/params.php
                  ;;
            esac

            make package

            case ${CIRCLE_BRANCH} in
                "production" )
                    echo "\nTransfering package...\n\n"
                    scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -J jump-user@141.94.251.125 package.zip kahe0589@109.234.162.184:/home/kahe0589/clubalpinlyon.fr
                    echo "\nTransfering deploy script...\n\n"
                    scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -J jump-user@141.94.251.125 .circleci/deploy.sh kahe0589@109.234.162.184:/home/kahe0589/clubalpinlyon.fr
                    echo "\nRunning deploy...\n\n"
                    LANG=en_US.utf8 LC_ALL=en_US.utf8 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kahe0589@109.234.162.184 -J jump-user@141.94.251.125 /home/kahe0589/clubalpinlyon.fr/deploy.sh clubalpinlyon.fr
                    echo "\nCleanup...\n\n"
                    LANG=en_US.utf8 LC_ALL=en_US.utf8 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kahe0589@109.234.162.184 -J jump-user@141.94.251.125 rm /home/kahe0589/clubalpinlyon.fr/deploy.sh /home/kahe0589/clubalpinlyon.fr/package.zip
                    echo "\nDone!\n\n"
                  ;;
                "main" )
                    echo "\nTransfering package...\n\n"
                    scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -J jump-user@141.94.251.125 package.zip kahe0589@109.234.162.184:/home/kahe0589/test.clubalpinlyon.fr
                    echo "\nTransfering deploy script...\n\n"
                    scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -J jump-user@141.94.251.125 .circleci/deploy.sh kahe0589@109.234.162.184:/home/kahe0589/test.clubalpinlyon.fr
                    echo "\nRunning deploy...\n\n"
                    LANG=en_US.utf8 LC_ALL=en_US.utf8 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kahe0589@109.234.162.184 -J jump-user@141.94.251.125 /home/kahe0589/test.clubalpinlyon.fr/deploy.sh test.clubalpinlyon.fr
                    echo "\nCleanup...\n\n"
                    LANG=en_US.utf8 LC_ALL=en_US.utf8 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kahe0589@109.234.162.184 -J jump-user@141.94.251.125 rm /home/kahe0589/test.clubalpinlyon.fr/deploy.sh /home/kahe0589/test.clubalpinlyon.fr/package.zip
                    echo "\nDone!\n\n"
                  ;;
            esac
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
