version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0
      # - image: circleci/mysql:5.7-ram

    steps:
      - checkout

      - run: sudo apt-get -yq update
      - run: sudo apt-get install ncftp

      - run: sudo composer self-update
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run:
          name: Deploy the codebase on the server
          command: |
            case ${CIRCLE_BRANCH} in
                "production" )
                    rm -rf .git
                    mv robots-production.txt robots.txt
                    sed -i "s/ADMIN_PASSWORD_TO_REPLACE/$PROD_ADMIN_PASSWORD/g" "config/www.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "config/www.clubalpinlyon.fr/params.php"
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$PROD_DB_PASSWORD/g" "config/www.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_USER_TO_REPLACE/$PROD_DB_USER/g" "config/www.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_NAME_TO_REPLACE/$PROD_DB_NAME/g" "config/www.clubalpinlyon.fr/db_config.php"
                    ncftpput -R -v -u $PROD_FTP_USERNAME -p $PROD_FTP_PASSWORD $FTP_SERVER . .
                  ;;
                "main" )
                    rm -rf .git
                    mv robots-dev.txt robots.txt
                    sed -i "s/ADMIN_PASSWORD_TO_REPLACE/$DEV_ADMIN_PASSWORD/g" "config/test.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "config/test.clubalpinlyon.fr/params.php"
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$DEV_DB_PASSWORD/g" "config/test.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_USER_TO_REPLACE/$DEV_DB_USER/g" "config/test.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_NAME_TO_REPLACE/$DEV_DB_NAME/g" "config/test.clubalpinlyon.fr/db_config.php"
                    ncftpput -R -v -u $DEV_FTP_USERNAME -p $DEV_FTP_PASSWORD $FTP_SERVER . .
                  ;;
            esac
