version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0
      # - image: circleci/mysql:5.7-ram

    steps:
      - checkout

      - run: sudo apt-get -yq update
      - run: sudo apt-get install ncftp openssh-client dnsutils
#      - run: dig rorotest.clubalpinlyon.fr
#      - run: ssh kahe0589@clubalpinlyon.fr ls

      - run: sudo composer self-update
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: composer install --no-dev --optimize-autoloader --no-interaction --apcu-autoloader --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run:
          name: Deploy the codebase on the server
          command: |
            case ${CIRCLE_BRANCH} in
                "production" )
                    rm -rf .git
                    mv public/robots-production.txt public/robots.txt
                    cp public/config/www.clubalpinlyon.fr/config.php public/config/config.php
                    sed -i "s/ADMIN_PASSWORD_TO_REPLACE/$PROD_ADMIN_PASSWORD/g" "public/config/www.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "public/config/www.clubalpinlyon.fr/params.php"
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$PROD_DB_PASSWORD/g" "public/config/www.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_USER_TO_REPLACE/$PROD_DB_USER/g" "public/config/www.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_NAME_TO_REPLACE/$PROD_DB_NAME/g" "public/config/www.clubalpinlyon.fr/db_config.php"
                    ncftpput -R -v -u $PRODUCTION_FTP_USERNAME -p $PRODUCTION_FTP_PASSWORD $FTP_SERVER . .
                  ;;
                "main" )
                    rm -rf .git
                    mv public/robots-dev.txt public/robots.txt
                    cp public/config/test.clubalpinlyon.fr/config.php public/config/config.php
                    sed -i "s/ADMIN_PASSWORD_TO_REPLACE/$DEV_ADMIN_PASSWORD/g" "public/config/test.clubalpinlyon.fr/params.php"
                    sed -i "s/MAILCHIMP_PASSWORD_TO_REPLACE/$MAILCHIMP_PASSWORD/g" "public/config/test.clubalpinlyon.fr/params.php"
                    sed -i "s/DB_PASSWORD_TO_REPLACE/$DEV_DB_PASSWORD/g" "public/config/test.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_USER_TO_REPLACE/$DEV_DB_USER/g" "public/config/test.clubalpinlyon.fr/db_config.php"
                    sed -i "s/DB_NAME_TO_REPLACE/$DEV_DB_NAME/g" "public/config/test.clubalpinlyon.fr/db_config.php"
                    ncftpput -R -v -u $STAGING_FTP_USERNAME -p $STAGING_FTP_PASSWORD $FTP_SERVER . .
                  ;;
            esac
