FROM php:7.2-apache
MAINTAINER Club Alpin Francais Chambery <webmaster@cafchambery.com>
#https://github.com/webgriffe/docker-php-apache-base
LABEL version="1.0"

# update
RUN apt-get update

# Install GD
RUN apt-get update \
	&& apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install gd

# Install Mysql for php
RUN docker-php-ext-install mysqli pdo_mysql

# Install mbstring
RUN docker-php-ext-install mbstring

# Install opcache
RUN docker-php-ext-install opcache

# Install XDEBUG
ENV XDEBUG_ENABLE 0
RUN pecl config-set preferred_state beta \
    && pecl install -o -f xdebug \
    && rm -rf /tmp/pear \
    && pecl config-set preferred_state stable

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Define PHP_TIMEZONE env variable
ENV PHP_TIMEZONE Europe/Paris

# Configure Apache Document Root
ENV APACHE_DOC_ROOT /var/www/html

# Additional configuration files
COPY ./utils/docker-999-php.ini /usr/local/etc/php/conf.d/999-php.ini
COPY ./utils/docker-99-xdebug.ini.disabled /usr/local/etc/php/conf.d/99-xdebug.ini.disabled
COPY ./utils/docker-phpinfo.php /var/www/html/phpinfo.php
COPY ./utils/docker-start-apache.sh /usr/local/bin/start-apache.sh
RUN chmod +x /usr/local/bin/start-apache.sh

# network
EXPOSE 80
EXPOSE 443

# Start!
CMD ["start-apache.sh"]
