framework:
  trusted_proxies: "%env(TRUSTED_PROXIES)%"
  trusted_headers:
    [
      "x-forwarded-for",
      "x-forwarded-host",
      "x-forwarded-proto",
      "x-forwarded-port",
      "x-forwarded-prefix",
    ]
  router:
        default_uri: 'https://%env(ROUTER_CONTEXT_HOST)%'