content:
    operation-en-cours: 'Opération en cours, veuillez patienter'
    meta-title-404: '404 : Page introuvable'
    mainmenu-accueil: Accueil
    mainmenu-contact: Contact
    meta-title-nouvelle-page-libre: 'Nouvelle page libre'
    meta-title-nouvelle-page-libre-2: 'Nouvelle page libre 2'
    meta-title-mot-de-passe-perdu: 'Mot de passe perdu ?'
    meta-title-profil: 'Mon profil'
    meta-title-user-confirm: 'Confirmation de votre compte'
    meta-title-infos: 'Mes infos'
    meta-title-sorties: 'Mes sorties'
    meta-title-articles: 'Mes articles'
    meta-title-photos: 'Mes photos'
    meta-title-filiation: Filiation
    meta-title-creer-une-sortie: 'Créer une sortie'
    site-meta-description: 'Decouverte et pratique de nombreuses activites de montagne : randonnee, raquette, ski, de randonnee, de fond, escalade, via ferrata, alpinisme, cascade de glace, vtt'
    meta-title-accueil: 'Club Alpin Français Lyon Villeurbanne'
    meta-title-pages: 'Club Alpin Lyon Villeurbanne'
    meta-title-gestion-des-sorties: 'Gestion des sorties'
    meta-title-contact: 'Contact - Club Alpin Lyon Villeurbanne CAF'
    logo-title: 'Toutes les commissions, sorties et actus du CAF Lyon Villeurbanne'
    news-title: 'Actualités - Club Alpin Lyon Villeurbanne CAF'
    userlink-title: 'Voir le profil'
    meta-title-sortie: Sortie
    meta-title-supprimer-une-sortie: 'Supprimer une sortie'
    meta-title-annuler-une-sortie: 'Annuler une sortie'
    meta-title-adherents: 'Liste des adhérents'
    meta-title-adherents-creer: 'Créer un adhérent'
    site-meta-title: 'Club Alpin Français Lyon Villeurbanne CAF'
    meta-title-agenda: 'Agenda des sorties - Club Alpin Lyon Villeurbanne CAF'
    meta-title-mentions-legales: 'Mentions légales - Club Alpin Français'
    meta-title-responsables: 'Responsables des commissions'
    meta-title-article-new: 'Nouvel article / Modifier un article'
    meta-title-article-edit: 'Modifier un article'
    meta-title-article: Article
    meta-title-gestion-des-articles: 'Gestion des articles'
    meta-title-recherche: 'Votre recherche'
    meta-title-commission-add: 'Créer une nouvelle commission'
    meta-title-gestion-des-commissions: 'Gestion des commissions'
    meta-title-partenaires-club: 'Partenaires du club'
    meta-description-partenaires-caf: partenaires_caf
    meta-title-commission-edit: 'Modifier une commission'
    meta-title-validation-des-sorties: 'Validation des sorties - Club Alpin Français'
    meta-title-stats: Statistiques
    meta-title-fichier-adherents: 'Mise à jour du fichier adhérent'
    meta-title-user-full: 'Fiche adhérent'
    meta-title-nos-partenaires-publics: 'Nos partenaires publics'
    meta-title-nos-partenaires-prives: 'Nos partenaires privés'
    meta-title-alpinisme: 'Alpinisme et cascade de glace'
    meta-description-alpinisme: Alpinisme
    meta-title-randonnee: Randonnée
    meta-description-randonnee: Randonnée
    meta-title-via-ferrata: 'Via ferrata'
    meta-description-via-ferrata: 'Via ferrata'
    meta-title-ski-de-randonnee: 'Ski de randonnée'
    meta-description-ski-de-randonnee: 'Ski de randonnée, ski-alpinisme, ski de montagne'
    meta-title-vtt: 'VTT Vélo de montagne'
    meta-description-vtt: 'VTT, velo de montagne, MTB, Mountain Bike au Club Alpin de Lyon Villeurbanne CAF'
    meta-title-canyon: Canyon
    meta-description-canyon: 'Canyon canyoning'
    meta-title-raquette: Raquette
    meta-description-raquette: Raquette
    meta-title-ski-de-piste: 'Ski de piste'
    meta-description-ski-de-piste: 'Ski piste alpin surf snowboard'
    meta-title-escalade: Escalade
    meta-title-ski-de-fond: 'Ski de fond'
    meta-title-environnement: 'Environnement durable'
    meta-title-ski-de-fond-technique: 'Ski de fond la technique'
    meta-title-ski-de-fond-pratique: 'Ski de fond détails pratiques'
    meta-title-ski-de-fond-biblio: 'Ski de fond bibliographie'
    meta-title-adhesion: 'Adhérer au CAF de Lyon Villeurbanne'
    meta-title-presentation: 'Présentation du club'
    meta-title-ouest-lyonnais: 'Section de l''Ouest Lyonnais'
    meta-title-refuges: 'Nos refuges'
    meta-title-chalet-de-bonneval-sur-arc: 'Chalet de Bonneval sur Arc'
    meta-title-refuge-d-averole: 'Refuge d''Avérole'
    meta-title-refuge-du-carro: 'Refuge du Carro'
    meta-title-refuge-des-evettes: 'Refuge des Evettes'
    meta-title-formation: Formation
    meta-title-test: 'Page de test'
    meta-title-destination: Destination
    meta-title-feuille-de-sortie: 'Feuille de sortie'
    meta-title-organisation-sorties: 'Organisation des sorties'
    meta-title-section-ouest-lyonnais: 'Section de l''Ouest Lyonnais'
    meta-title-escalade-programme: 'Programme escalade 2017-2018'
    meta-description-escalade-programme: 'programme escalade 2017-2018'
    meta-title-trail: Trail
    meta-title-retour-paiement-en-ligne: 'Retour paiement en ligne'
    meta-description-retour-paiement-en-ligne: 'infos après paiement en ligne'
    meta-title-snowboard-de-randonnee: 'Snowboard de randonnée'
    meta-description-snowboard-de-randonnee: 'snowboard, spliboard, surf'
    meta-title-snowboard-rando: 'Snowboard de randonnée'
    meta-description-snowboard-rando: 'snowboard, spliboard, surf'
    meta-title-jeunes: 'Un CAF pour les Jeunes !'
    meta-description-jeunes: 'Le Club Alpin, c''est aussi pour les Jeunes !'
    meta-title-ecole-escalade: 'École d''escalade'
    meta-description-ecole-escalade: 'Le Club Alpin, c''est aussi pour les Jeunes : l''école d''escalade !'
    meta-title-ecole-aventure: 'École d''aventure'
    meta-title-marche-nordique: 'Marche nordique'
    meta-title-groupe-jeunes-alpinistes: 'Groupe Jeunes Alpinistes'
    meta-title-problemes-de-connexion: 'Problèmes de connexion ?'
