#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_legacy:
    resource: .
    type: legacy

app_logout:
    path: "/logout"

session_email_check:
    path: "/session/check/email"
