# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  legacy_env_ANALYTICS_ACCOUNT: "%env(string:ANALYTICS_ACCOUNT)%"
  legacy_env_GOOGLE_SITE_VERIFICATION: "%env(string:GOOGLE_SITE_VERIFICATION)%"
  legacy_env_MAIL_EMITTER_EMAIL: "%env(string:MAIL_EMITTER_EMAIL)%"
  legacy_env_MAIL_EMITTER_NAME: "%env(string:MAIL_EMITTER_NAME)%"
  legacy_env_CONTENT_MAX_VERSIONS: "%env(int:CONTENT_MAX_VERSIONS)%"
  legacy_env_CRON_DATE_BUTOIRES: "%env(json:CRON_DATE_BUTOIRES)%"
  legacy_env_MAX_TIMESTAMP_FOR_LEGAL_VALIDATION: "%env(string:MAX_TIMESTAMP_FOR_LEGAL_VALIDATION)%"
  legacy_env_MAX_ADMINS_SUB_LEVELS: "%env(int:MAX_ADMINS_SUB_LEVELS)%"
  legacy_env_MAX_ARTICLES_VALIDATION: "%env(int:MAX_ARTICLES_VALIDATION)%"
  legacy_env_MAX_SORTIES_VALIDATION: "%env(int:MAX_SORTIES_VALIDATION)%"
  legacy_env_MAX_ARTICLES_ADHERENT: "%env(int:MAX_ARTICLES_ADHERENT)%"
  legacy_env_MAX_ARTICLES_ACCUEIL: "%env(int:MAX_ARTICLES_ACCUEIL)%"
  legacy_env_MAX_IMAGE_SIZE: "%env(int:MAX_IMAGE_SIZE)%"
  legacy_env_DISPLAY_BANNER: "%env(bool:DISPLAY_BANNER)%"
  legacy_env_DISPLAY_NOTES_DE_FRAIS: "%env(bool:DISPLAY_NOTES_DE_FRAIS)%"
  legacy_ftp_path: "%public_dir%/ftp/"
  legacy_project_dir: "%kernel.project_dir%"
  legacy_env_SITENAME: "%env(string:SITENAME)%"
  legacy_env_SENTRY_DSN: "%env(string:SENTRY_DSN)%"
  legacy_env_DB_HOST: "%env(string:DB_HOST)%"
  legacy_env_DB_PORT: "%env(int:DB_PORT)%"
  legacy_env_DB_USER: "%env(string:DB_USER)%"
  legacy_env_DB_PASSWORD: "%env(string:DB_PASSWORD)%"
  legacy_env_DB_NAME: "%env(string:DB_NAME)%"
  router.request_context.scheme: "%env(string:ROUTER_REQUEST_CONTEXT_SCHEME)%"
  asset.request_context.secure: "%env(bool:ASSET_REQUEST_CONTEXT_SECURE)%"
  public_dir: "%kernel.project_dir%/public"
  expense_report:
        nuiteeMaxRemboursable: 60
        tauxKilometriqueVoiture: 0.2
        tauxKilometriqueMinibus: 0.3
        divisionPeage: 3
  materiel_api_base_url: "%env(LOXYA_API_URL)%"
  materiel_api_username: "%env(LOXYA_API_USERNAME)%"
  materiel_api_password: "%env(LOXYA_API_PASSWORD)%"
  materiel_platform_url: "%env(LOXYA_PLATFORM_URL)%"
  default_latitude: '%env(DEFAULT_LATITUDE)%'
  default_longitude: '%env(DEFAULT_LONGITUDE)%'
  default_appmt_place: '%env(DEFAULT_APPMT_PLACE)%'
  app_instance_name: '%env(APP_INSTANCE_NAME)%'
  mobile_app_deeplink_scheme: '%env(MOBILE_APP_DEEPLINK_SCHEME)%'
  mobile_app_minimum_version: '%env(MOBILE_APP_MINIMUM_VERSION)%'
  api_version: '%env(API_VERSION)%'
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $kernelProjectDir: "%kernel.project_dir%"
      $kernelCacheDir: "%kernel.cache_dir%"
      $kernelEnvironment: "%kernel.environment%"
      $recaptchaSecret: "%env(RECAPTCHA_SECRET)%"
      $baseUrl: "%env(BACKEND_URL)%"
      $legacyFtpPath: "%legacy_ftp_path%"

  # allows access to service container as an injected dependency
  Symfony\Component\DependencyInjection\ContainerInterface: "@service_container"

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Twig\JwtExtension:
    public: true
    tags:
      - { name: "twig.extension" }

  App\Twig\JavascriptGlobalsExtension:
    tags: ["twig.extension"]

  App\Twig\AppExtension:
    tags: ["twig.extension"]

  App\Legacy\LegacyRouteLoader:
    tags: ["routing.loader"]

  Egulias\EmailValidator\EmailValidator: ~

  App\Repository\CommissionRepository:
    public: true

  App\Service\EmailMarketingSyncService:
    public: true
    arguments:
      $mailerLiteService: '@?App\Service\MailerLiteService'

  App\Mailer\Mailer:
    arguments:
      $replyTo: "%env(MAIL_EMITTER_EMAIL)%"
      $nameEmitter: "%env(MAIL_EMITTER_NAME)%"

  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    public: true
    arguments:
      - "%env(DATABASE_URL)%"

  App\Controller\AdminController:
    arguments:
      $adminPassword: "%env(PASSWORD_ADMIN)%"
      $contentManagerPassword: "%env(PASSWORD_CONTENT_MANAGER)%"

  App\Controller\RssController:
    arguments:
      $sitename: "%env(SITENAME)%"

  App\EventListener\ForceHttpsListener:
    arguments:
      $appEnv: "%kernel.environment%"
      $appName: "%env(CC_APP_NAME)"

  App\Bridge\Twig\TwigExtension:
    arguments:
      $maxTimestampForLegalValidation: "%env(MAX_TIMESTAMP_FOR_LEGAL_VALIDATION)%"

  App\Security\Voter\ExpenseReportVoter:
    arguments:
      $authorizedManagerIds: "%env(string:AUTHORIZED_IDS_FOR_EXPENSE_MANAGEMENT)%"

  Symfony\Component\String\Slugger\SluggerInterface:
    class: Symfony\Component\String\Slugger\AsciiSlugger

  App\Messenger\MessageHandler\UserNotificationHandler:
    arguments:
      $defaultAlertArticlePrefix: "%env(ALERT_ARTICLE_PREFIX)%"
      $defaultAlertSortiePrefix: "%env(ALERT_SORTIE_PREFIX)%"

  # Email Marketing Services Configuration
  App\Service\MailerLiteService:
    arguments:
      $apiKey: "%env(MAILERLITE_API_KEY)%"
      $welcomeGroupId: "%env(MAILERLITE_WELCOME_GROUP_ID)%"

  App\Service\ExpenseReportCalculator:
    arguments:
      $config: '%expense_report%'
            
  # services used in legacy
  legacy_router:
    public: true
    alias: "router"

  # services used in legacy
  legacy_token_storage:
    public: true
    alias: "security.token_storage"

  legacy_csrf_token_manager:
    public: true
    alias: Symfony\Component\Security\Csrf\CsrfTokenManagerInterface

  legacy_message_bus:
    public: true
    alias: Symfony\Component\Messenger\MessageBusInterface

  legacy_twig:
    public: true
    alias: Twig\Environment

  legacy_fs:
    public: true
    alias: Symfony\Component\Filesystem\Filesystem

  legacy_request_stack:
    public: true
    alias: Symfony\Component\HttpFoundation\RequestStack

  legacy_hasher_factory:
    public: true
    alias: Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface

  legacy_logger:
    public: true
    alias: "logger"

  legacy_user_rights:
    public: true
    class: App\UserRights

  legacy_mysqli_handler:
    public: true
    class: App\Utils\MysqliHandler

  legacy_imagine:
    public: true
    class: Imagine\Imagick\Imagine

  legacy_authorization_checker:
    public: true
    alias: Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface

  legacy_mailer:
    public: true
    alias: App\Mailer\Mailer

  legacy_content_html:
    public: true
    alias: App\Legacy\ContentHtml

  legacy_user_repository:
    public: true
    alias: App\Repository\UserRepository

  legacy_member_merger:
    public: true
    alias: App\Utils\MemberMerger

  App\Utils\User\UserProfileValidator:
    public: true

  legacy_content_inline:
    public: true
    alias: App\Legacy\ContentInline

  legacy_entrypoint_renderer:
    public: true
    alias: App\Legacy\LegacyEntrypointRenderer

  App\Utils\FileUploader:
    arguments:
      $publicDir: '%public_dir%'

  App\Command\FfcamFileSync:
    arguments:
      $ffcamFilePath: "%env(FFCAM_FILE_PATH)%"

  App\EventListener\ExpenseReportStatusListener:
    tags:
      - { name: doctrine.event_listener, event: preUpdate }

  App\Service\MaterielApiService:
    arguments:
      $apiBaseUrl: '%materiel_api_base_url%'
      $apiUsername: '%materiel_api_username%'
      $apiPassword: '%materiel_api_password%'

  App\Service\MaterielEmailService:
    arguments:
      $materielPlatformUrl: '%materiel_platform_url%'

  App\Form\EventType:
    arguments:
      $club: '%env(CAF_ID)%'
    tags: ['form.type']

  App\Controller\SortieController:
    arguments:
      $defaultLat: '%default_latitude%'
      $defaultLong: '%default_longitude%'
      $defaultAppointmentPlace: '%default_appmt_place%'
    tags: ['controller.service_arguments']

  App\Service\PushNotificationService:
    arguments:
      $appInstanceName: '%app_instance_name%'
      $appDeeplinkScheme: '%mobile_app_deeplink_scheme%'
      $sitename: '%legacy_env_SITENAME%'

  App\Serializer\PaginationMetadataNormalizer:
    tags:
      - { name: 'serializer.normalizer', priority: 64 }
      
  App\Doctrine\ExpenseReportExtension:
    tags:
      - { name: 'api_platform.doctrine.orm.query_extension.collection' }
      - { name: 'api_platform.doctrine.orm.query_extension.item' }

  legacy_user_right_service:
    public: true
    alias: App\Service\UserRightService
