name: Code Quality
on: [pull_request]

jobs:
  php-cs:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour avoir l'historique git complet

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none
          tools: cs2pr, phive

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache PHP-CS-Fixer
        uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-php-cs-fixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-php-cs-fixer-
            ${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --ignore-platform-req=ext-uopz

      - name: Install PHP tools
        run: phive install --copy --trust-gpg-keys 8E730BA25823D8B5,CF1A108D0E7AE720,E82B2FB314E9906E,CA7C2C7A30C8E8E1274A847651C67305FFC2E5C0

      # Pour les PR : analyse seulement les fichiers modifiés
      - name: Get changed PHP files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.pull_request.base.sha }} | grep -E '\.php$' | xargs -r ls 2>/dev/null | paste -sd " " || true)
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          if [ -z "$CHANGED_FILES" ]; then
            echo "No PHP files changed"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "PHP files changed: $CHANGED_FILES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Run PHP-CS-Fixer on changed files
        if: steps.changed-files.outputs.has_changes == 'true'
        run: |
          echo "Running PHP-CS-Fixer with parallel processing..."
          ./bin/tools/php-cs-fixer fix --dry-run --diff --format=checkstyle --config=.php-cs-fixer.dist.php ${{ steps.changed-files.outputs.files }} | cs2pr

      - name: Run PHP-CS-Fixer (no changes)
        if: steps.changed-files.outputs.has_changes == 'false'
        run: echo "✅ No PHP files to check"

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pour l'analyse différentielle
      
      - name: Prepare environment
        uses: ./.github/actions/prepare
      
      - name: Cache PHPStan result cache
        uses: actions/cache@v4
        with:
          path: /tmp/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpstan-
            ${{ runner.os }}-

      - name: Install PHPStan
        run: |
          mkdir -p bin/tools
          curl -L https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar -o bin/tools/phpstan
          chmod +x bin/tools/phpstan

      # Pour les PR : analyse seulement les fichiers modifiés
      - name: Get changed PHP files for PHPStan
        id: changed-php-files
        if: github.event_name == 'pull_request'
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.pull_request.base.sha }} | grep -E '\.php$' | grep -E '^(src|tests|legacy)/' | xargs -r ls 2>/dev/null | paste -sd " " || true)
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          if [ -z "$CHANGED_FILES" ]; then
            echo "No relevant PHP files changed for PHPStan"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "PHP files changed: $CHANGED_FILES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Run PHPStan on changed files
        if: github.event_name == 'pull_request' && steps.changed-php-files.outputs.has_changes == 'true'
        run: |
          echo "Running PHPStan on changed files with parallel processing..."
          ./bin/tools/phpstan analyse ${{ steps.changed-php-files.outputs.files }} -c phpstan.neon
      
      - name: Run PHPStan (full analysis)
        if: github.event_name != 'pull_request'
        run: make phpstan
      
      - name: Skip PHPStan (no changes)
        if: github.event_name == 'pull_request' && steps.changed-php-files.outputs.has_changes == 'false'
        run: echo "✅ No relevant PHP files to analyze"