name: Test
on: [pull_request]

jobs:
  php-cs:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare environment
        uses: ./.github/actions/prepare
        
      - name: Run php-cs
        run: make php-cs

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare environment
        uses: ./.github/actions/prepare
      
      - name: Setup phpunit
        run: make phpunit-setup
        
      - name: Run phpstan
        run: make phpstan

  tests:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare environment
        uses: ./.github/actions/prepare
        
      - name: Initialise the database
        run: |
          make database-init-test
      - name: Run tests
        run: make tests
