on: [pull_request]
name: Test

jobs:
  make-php-cs:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the environment
        run: |
          export UID_OVERRIDE="$UID"
          export GID_OVERRIDE="$GID"
          make init
      - name: Run the linter
        run: |
          make args=--diff php-cs

  make-phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the environment
        run: |
          export UID_OVERRIDE="$UID"
          export GID_OVERRIDE="$GID"
          make init
      - name: Setup PHPUnit
        run: |
          make phpunit-setup
      - name: Run phpstan
        run: |
          make phpstan

  make-test:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the environment
        run: |
          export UID_OVERRIDE="$UID"
          export GID_OVERRIDE="$GID"
          make init
      - name: Initialise the database
        run: |
          make database-init-test
      - name: Run the unit tests
        # For an obscure reason, the exit code is 0 even if there are errors.
        # So we need to grep the output to check if there are errors.
        run: |
          make tests 2>&1 | tee test_output.txt
          if grep -E "ERRORS!|There was [0-9]+ failures" test_output.txt; then
            exit 1
          fi
